all: part1 part2 part3

part1: part_1.cpp
	g++ part_1.cpp -o part1 -fopenmp

part2: part_2.cpp
	g++ part_2.cpp -o part2 -fopenmp

part3: part_3.cpp
	g++ part_3.cpp -o part3 -fopenmp

clean:
	rm -f part1 part2 part3
